# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @noRd
known_fit_aphids0 <- function(pars, L, re, time, max_shape) {
    .Call(`_aphidsync_known_fit_aphids0`, pars, L, re, time, max_shape)
}

#' @export
#' @noRd
beta_starts <- function(shape, offset, total_aphids0, compartments = 29L) {
    .Call(`_aphidsync_beta_starts`, shape, offset, total_aphids0, compartments)
}

#' @export
#' @noRd
make_L1 <- function(shape, scale) {
    .Call(`_aphidsync_make_L1`, shape, scale)
}

#' @export
#' @noRd
unknown_fit_aphids0 <- function(pars, re, time, max_f, fit_survs, max_shape) {
    .Call(`_aphidsync_unknown_fit_aphids0`, pars, re, time, max_f, fit_survs, max_shape)
}

