# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @noRd
beta_starts <- function(shape, offset, total_aphids0, compartments = 29L) {
    .Call(`_aphidsync_beta_starts`, shape, offset, total_aphids0, compartments)
}

#' @export
#' @noRd
make_L1 <- function(shape, scale) {
    .Call(`_aphidsync_make_L1`, shape, scale)
}

#' @export
#' @noRd
optim_L <- function(shape, scale, lambda, method = "BOBYQA", upper_bound = 1000, tol = 1e-4, max_iters = 1000L) {
    .Call(`_aphidsync_optim_L`, shape, scale, lambda, method, upper_bound, tol, max_iters)
}

#' @export
#' @noRd
make_regr_ptr <- function() {
    .Call(`_aphidsync_make_regr_ptr`)
}

#' @export
#' @noRd
calc_L <- function(shape, scale, lambda) {
    .Call(`_aphidsync_calc_L`, shape, scale, lambda)
}

#' @export
#' @noRd
fit_aphids0 <- function(pars, known_L, re, time, fecund, regr_ptr, match_lambda = FALSE, max_shape = 800, L_method = "BOBYQA", L_upper_bound = 1000, L_tol = 1e-4, L_max_iters = 1000L) {
    .Call(`_aphidsync_fit_aphids0`, pars, known_L, re, time, fecund, regr_ptr, match_lambda, max_shape, L_method, L_upper_bound, L_tol, L_max_iters)
}

