# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @noRd
known_fit_aphids0 <- function(pars, K, L, obs, time, max_shape, compare_N = FALSE) {
    .Call(`_aphidsync_known_fit_aphids0`, pars, K, L, obs, time, max_shape, compare_N)
#' Calculate lambda (exponential growth rate) from Leslie matrix.
#'
#' @param L Leslie matrix.
#'
#' @export
#'
calc_lambda <- function(L) {
    .Call(`_aphidsync_calc_lambda`, L)
}

#' Width of 99th quartile
#'
#' @param shape Vector of shape parameters for the symmetrical beta
#'     distribution of abundances.
#'
#' @export
#'
width99 <- function(shape) {
    .Call(`_aphidsync_width99`, shape)
}

#' Median age
#'
#' @inheritParams width99
#' @param offset Vector of offset value(s) for the symmetrical beta
#'     distribution of abundances.
#'     Must be the same length as `shape`.
#'
#' @export
#'
med_age <- function(shape, offset, n_stages = 29L) {
    .Call(`_aphidsync_med_age`, shape, offset, n_stages)
}

#' Logit and inverse logit functions.
#'
#'
#' @name logit
#' @export
#'
logit <- function(p) {
    .Call(`_aphidsync_logit`, p)
}

#' @describeIn logit
#'
#' @export
#'
inv_logit <- function(a) {
    .Call(`_aphidsync_inv_logit`, a)
}

#' @export
#' @noRd
beta_starts <- function(shape, offset, total_aphids0, compartments = 29L) {
    .Call(`_aphidsync_beta_starts`, shape, offset, total_aphids0, compartments)
}

#' @export
#' @noRd
make_L1 <- function(shape, scale) {
    .Call(`_aphidsync_make_L1`, shape, scale)
}

#' Simulate per-capita growth.
#'
#' @export
#' @noRd
sim_re <- function(aphids0, L, time, K) {
    .Call(`_aphidsync_sim_re`, aphids0, L, time, K)
}

#' Simulate abundance.
#'
#' @export
#' @noRd
sim_N <- function(aphids0, L, time, K) {
    .Call(`_aphidsync_sim_N`, aphids0, L, time, K)
}

#' @export
#' @noRd
unknown_fit_aphids0 <- function(pars, re, time, max_f, fit_survs, max_shape) {
    .Call(`_aphidsync_unknown_fit_aphids0`, pars, re, time, max_f, fit_survs, max_shape)
}

